### ISSUE TITLE
No module named 'resource'

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#1]
blechpy/ultils/memory_monitor.py depends on module 'resource'. resource is a unix-specific module, so Windows users cannot use blechpy. Temporary solution for Windows users will be to run blechpy on Ubuntu on dual-boot or virtual machine, and for Katz-lab users, on jetstream.

**Comment by nubs01** [comment]
resource should be a built in python module. Are you using miniconda?

**Comment by nubs01** [comment]
Oh resource is a unix specific package. blechpy is only meant to run on
linux.
