### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by abuzarmahmood** [nubs01/blechpy#10]
>>> ipython
>>> import blechpy

ImportError                               Traceback (most recent call last)
<ipython-input-2-40b0b4a96353> in <module>()
----> 1 import blechpy

~/anaconda3/lib/python3.6/site-packages/blechpy/__init__.py in <module>()
----> 1 from blechpy.datastructures.objects import load_experiment, load_dataset, load_project
      2 from blechpy.datastructures.dataset import dataset, port_in_dataset
      3 from blechpy.datastructures.experiment import experiment
      4 from blechpy.datastructures.project import project
      5 from blechpy import dio, analysis, utils, plotting

~/anaconda3/lib/python3.6/site-packages/blechpy/datastructures/objects.py in <module>()
      1 import os
----> 2 from blechpy.utils import userIO
      3 import pickle
      4 
      5 class data_object(object):

~/anaconda3/lib/python3.6/site-packages/blechpy/utils/__init__.py in <module>()
      3 from . import particles
      4 from . import print_tools
----> 5 from . import write_tools
      6 from . import tk_widgets
      7 from . import spike_sorting_GUI

~/anaconda3/lib/python3.6/site-packages/blechpy/utils/write_tools.py in <module>()
----> 1 from blechpy.utils import print_tools as pt, userIO
      2 import pandas as pd
      3 import json
      4 import os
      5 

~/anaconda3/lib/python3.6/site-packages/blechpy/utils/userIO.py in <module>()
     10 from prompt_toolkit.history import InMemoryHistory
     11 from prompt_toolkit.shortcuts import prompt as pt_prompt
---> 12 from prompt_toolkit.completion import PathCompleter
     13 
     14 

ImportError: cannot import name 'PathCompleter'

<<< VERSION DETAILS >>>

>>> pip show blechpy
Name: blechpy
Version: 2.0.21
Summary: Package for exrtacting, processing and analyzing Intan and OpenEphys data
Home-page: https://github.com/nubs01/blechpy
Author: Roshan Nanu
Author-email: roshan.nanu@gmail.com
License: UNKNOWN
Location: /home/abuzarmahmood/anaconda3/lib/python3.6/site-packages
Requires: holoviews, scikit-learn, h5py, easygui, entrypoints, datashader, mistune, numba, tqdm, pygments, umap-learn, seaborn, scipy, tables, numpy, jupyter-core, appdirs, statsmodels, ipython, matplotlib, joblib
Required-by:

**Comment by nubs01** [comment]
pip install prompt-toolkit
I'll add it to the requirements

**Comment by abuzarmahmood** [comment]
Dope! Thanks :)
