### ISSUE TITLE
Running blech_clust_run(umap = True) doesn't actually cluster anything

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#13]
https://github.com/nubs01/blechpy/blob/d462ab7043f773f330c849ecfaedda507988e1fd/blechpy/datastructures/dataset.py#L812

Clustering Complete
------------------
Errors encountered:
[LoweringError('\x1b[1mFailed in nopython mode pipeline (step: nopython mode backend)\n\x1b[1m\x1b[1margs\n\x1b[1m\nFile "../opt/anaconda/anaconda3/lib/python3.7/site-packages/umap/umap_.py", line 455:\x1b[0m\n\x1b[1mdef compute_membership_strengths(knn_indices, knn_dists, sigmas, rhos):\n    <source elided>\n\n\x1b[1m    rows = np.zeros(knn_indices.size, dtype=np.int32)\n\x1b[0m    \x1b[1m^\x1b[0m\x1b[0m\n\x1b[0m\n\x1b[0m\x1b[1m[1] During: lowering "id=1[LoopNest(index_variable = parfor_index.167, range = (0, $0.12, 1))]{286: <ir.Block at /opt/anaconda/anaconda3/lib/python3.7/site-packages/umap/umap_.py (455)>}Var(parfor_index.167, /opt/anaconda/anaconda3/lib/python3.7/site-packages/umap/umap_.py (455))" at /opt/anaconda/anaconda3/lib/python3.7/site-packages/umap/umap_.py (455)\x1b[0m\n\n-------------------------------------------------------------------------------\nThis should not have happened, a problem has occurred in Numba\'s internals.\nYou are currently using Numba version 0.46.0.\n\nPlease report the error message and traceback, along with a minimal reproducer\nat: https://github.com/numba/numba/issues/new\n\nIf more help is needed please feel free to speak to the Numba core developers\ndirectly at: https://gitter.im/numba/numba\n\nThanks in advance for your help in improving Numba!\n\n\x1b[0m'), LoweringError('\x1b[1mFailed in nopython mode pipeline (step: nopython mode backend)\n\x1b[1m\x1b[1margs\n\x1b[1m\nFile "../opt/anaconda/anaconda3/lib/python3.7/site-packages/umap/umap_.py", line 455:\x1b[0m\n\x1b[1mdef compute_membership_strengths(knn_indices, knn_dists, sigmas, rhos):\n    <source elided>\n\n\x1b[1m    rows = np.zeros(knn_indices.size, dtype=np.int32)\n\x1b[0m    \x1b[1m^\x1b[0m\x1b[0m\n\x1b[0m\n\x1b[0m\x1b[1m[1] During: lowering "id=1[LoopNest(index_variable = parfor_index.167, range = (0, $0.12, 1))]{286: <ir.Block at /opt/anaconda/anaconda3/lib/python3.7/site-packages/umap/umap_.py (455)>}Var(parfor_index.167, /opt/anaconda/anaconda3/lib/python3.7/site-packages/umap/umap_.py (455))" at /opt/anaconda/anaconda3/lib/python3.7/site-packages/umap/umap_.py

Running the function resulted in the program hanging for a few minutes at 0% and then displaying "clustering complete!" Interestingly I could sort spikes after and it deleted the raw data in the HDF5, so the function clearly reported that clustering had happened.

**Comment by nubs01** [comment]
Remind me, did we solve this? Was it a dependency versioning issue?

**Comment by danielsvedberg** [comment]
> Remind me, did we solve this? Was it a dependency versioning issue?

This was the dependency issue, but using your blechpy_environment.yml file doesn't fix this in Ubuntu 20.04

**Comment by nubs01** [comment]
Gonna need you to run it with multi_process=False, but yeah I'm not sure
what this error is. If you could get me the recording on a USB or send it
to via Google drive, I can try to run the clustering on my home machine
which is Ubuntu 20 and see if it works. Complicated issues are easier to
debug if I can recreate them.

**Comment by danielsvedberg** [comment]
fixed with blechpy update 2.1.0

**Comment by danielsvedberg** [comment]
fixed with blechpy update 2.1.0
