### ISSUE TITLE
np.arange() is used but not numpy is not imported. 

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#16]
https://github.com/nubs01/blechpy/blob/13aca4be99dab117eb176c6b5cda54e80d715de5/blechpy/datastructures/dataset.py#L1206

L1206 throws an error when running dat.port_in_dataset() that I believe is caused by not importing numpy

**Comment by danielsvedberg** [comment]
Also heads up, this issue pops up 4 times in dataset.py, so if you fix this issue without importing numpy, make sure to catch those as well.

**Comment by nubs01** [comment]
Good catch. Took numpy for granted.
