### ISSUE TITLE
Segmentation Fault (core dumped) when importing blechpy

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#17]
I'm just going to put this issue up since it's technically still "an issue" and so people can refer to it (and the workaround) in the future

On Ubuntu 20+, the following happens when importing blechpy:

<pre><font color="#008700">In [</font><font color="#8AE234"><b>1</b></font><font color="#008700">]: </font><font color="#008700"><b>import</b></font> <font color="#0087D7"><b>blechpy</b></font>                                                                                                                                                                          
Segmentation fault (core dumped)
</pre>

The workaround is to first import datashader, and THEN import blechpy whenever you start a session.

**Comment by nubs01** [comment]
Yes thanks Dan. I also added it to the readme since I still haven't found a
way to solve this and I have no idea why it happens.

**Comment by danielsvedberg** [comment]
[This thread explains that the build for numba==0.48.0 that you get when you pip install numba is broken.](https://github.com/numba/numba/issues/4515) This issue is completely resolved if you instead use conda install numba==0.48.0!
