### ISSUE TITLE
blech_clust_run(umap=True) throws various warnings but runs anyways 

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#18]
Running Ubuntu 20.04 LTS 
**Note: if you're troubleshooting this step and get these same messages, but blechpy doesn't crash, let it run for a while and the end result will be fine. This is a low-priority issue, I've mainly raised it to spread awareness that getting these error messages is not a problem per-se.** 

Whenever I run dat.blech_clust_run(umap=True), I get the following warnings:

<pre><font color="#008700">In [</font><font color="#8AE234"><b>7</b></font><font color="#008700">]: </font>dat.blech_clust_run(umap = <font color="#008700"><b>True</b></font>)                                                                                                                                                        
Running Blech Clust...
[Parallel(n_jobs=11)]: Using backend MultiprocessingBackend with 11 concurrent workers.
/home/dsvedberg/anaconda3/envs/blechpy/lib/python3.7/site-packages/numba/typed_passes.py:293: NumbaPerformanceWarning: 
The keyword argument &apos;parallel=True&apos; was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File &quot;home/dsvedberg/anaconda3/envs/blechpy/lib/python3.7/site-packages/umap/rp_tree.py&quot;, line 135:
@numba.njit(fastmath=True, nogil=True, parallel=True)
def euclidean_random_projection_split(data, indices, rng_state):
^

  state.func_ir.loc))
/home/dsvedberg/anaconda3/envs/blechpy/lib/python3.7/site-packages/umap/nndescent.py:92: NumbaPerformanceWarning: 
The keyword argument &apos;parallel=True&apos; was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see http://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File &quot;home/dsvedberg/anaconda3/envs/blechpy/lib/python3.7/site-packages/umap/utils.py&quot;, line 409:
@numba.njit(parallel=True)
def build_candidates(current_graph, n_vertices, n_neighbors, max_candidates, rng_state):
^

</pre>

these messages seem to repeat themselves over and over again, seemingly for once for each batch of parallel processes.

**Comment by danielsvedberg** [comment]
I believe this problem may be related to module versioning. Here is my pip freeze output:
<pre>appdirs==1.4.4
backcall==0.1.0
blechpy==2.1.0
bokeh==1.4.0
certifi==2019.11.28
cffi==1.14.5
chardet==4.0.0
Click==7.0
cloudpickle==1.3.0
colorcet==2.0.2
cryptography==3.4.7
cycler==0.10.0
dask==2.11.0
datashader==0.10.0
datashape==0.5.2
decorator==4.4.2
dill==0.3.1.1
distributed==2.11.0
easygui==0.98.1
entrypoints==0.3
feather-format==0.4.1
fsspec==0.6.2
h5py==2.10.0
HeapDict==1.0.1
holoviews==1.12.7
idna==2.10
imageio==2.8.0
importlib-metadata==4.6.0
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.16.0
jeepney==0.6.0
Jinja2==2.11.1
joblib==0.14.1
jupyter-core==4.6.3
keyring==23.0.1
keyrings.alt==4.0.2
kiwisolver==1.1.0
littleutils==0.2.2
llvmlite==0.31.0
locket==0.2.0
Mako==1.1.3
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib==3.2.0
mistune==0.8.4
msgpack==1.0.0
multipledispatch==0.6.0
networkx==2.4
numba==0.48.0
numexpr==2.7.1
numpy==1.18.1
outdated==0.2.0
packaging==20.3
pandas==1.0.1
pandas-flavor==0.2.0
param==1.9.3
parso==0.6.2
partd==1.1.0
patsy==0.5.1
pdoc3==0.9.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pingouin==0.3.8
prompt-toolkit==3.0.3
psutil==5.7.0
ptyprocess==0.6.0
pushbullet-tools==0.0.7
pyarrow==0.17.0
pycparser==2.20
pyct==0.4.6
Pygments==2.9.0
pyparsing==2.4.6
python-dateutil==2.8.1
pytz==2019.3
pyviz-comms==0.7.3
PyWavelets==1.1.1
PyYAML==5.3
requests==2.25.1
scikit-image==0.16.2
scikit-learn==0.22.2.post1
scipy==1.3.3
seaborn==0.11.1
SecretStorage==3.3.1
six==1.16.0
sortedcontainers==2.1.0
statsmodels==0.11.1
tables==3.6.1
tabulate==0.8.7
tblib==1.6.0
toolz==0.10.0
tornado==6.0.4
tqdm==4.61.1
traitlets==4.3.3
typing-extensions==3.10.0.0
umap-learn==0.3.10
urllib3==1.26.6
wcwidth==0.1.8
xarray==0.15.0
zict==2.0.0
zipp==3.4.1
</pre>

**Comment by nubs01** [comment]
Can you post the warnings you get?

**Comment by danielsvedberg** [comment]
> Can you post the warnings you get?
I accidentally hit enter when I created the issue before I got to write any of the body text, I put the warnings in the body text edit right after editing the title

**Comment by danielsvedberg** [comment]
Just verified that these warnings appear when blech_clust_run(multi_processing=False)
