### ISSUE TITLE
Error importing blechpy over ssh

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#21]
I also imported datashader before this, 

In [2]: import blechpy                                                                                                               
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-40b0b4a96353> in <module>
----> 1 import blechpy

~/anaconda3/envs/blechpy/lib/python3.7/site-packages/blechpy/__init__.py in <module>
----> 1 from blechpy.datastructures.objects import load_experiment, load_dataset, load_project
      2 from blechpy.datastructures.dataset import dataset, port_in_dataset
      3 from blechpy.datastructures.experiment import experiment
      4 from blechpy.datastructures.project import project
      5 from blechpy import dio, analysis, utils, plotting

~/anaconda3/envs/blechpy/lib/python3.7/site-packages/blechpy/datastructures/objects.py in <module>
      1 import os
----> 2 from blechpy.utils import userIO
      3 import pickle
      4 
      5 class data_object(object):

~/anaconda3/envs/blechpy/lib/python3.7/site-packages/blechpy/utils/__init__.py in <module>
      5 from . import write_tools
      6 from . import tk_widgets
----> 7 from . import spike_sorting_GUI
      8 from . import data_reset

~/anaconda3/envs/blechpy/lib/python3.7/site-packages/blechpy/utils/spike_sorting_GUI.py in <module>
      5 import matplotlib
      6 from blechpy.utils import userIO, tk_widgets as tkw
----> 7 matplotlib.use('TkAgg')
      8 import matplotlib.pyplot as plt
      9 from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

~/anaconda3/envs/blechpy/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    294                 f"for the old name will be dropped %(removal)s.")
    295             kwargs[new] = kwargs.pop(old)
--> 296         return func(*args, **kwargs)
    297 
    298     # wrapper() must keep the same documented signature as func(): if we

~/anaconda3/envs/blechpy/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py in wrapper(*args, **kwargs)
    356                 f"%(removal)s.  If any parameter follows {name!r}, they "
    357                 f"should be pass as keyword, not positionally.")
--> 358         return func(*args, **kwargs)
    359 
    360     return wrapper

~/anaconda3/envs/blechpy/lib/python3.7/site-packages/matplotlib/__init__.py in use(backend, warn, force)
   1257         try:
   1258             from matplotlib import pyplot as plt
-> 1259             plt.switch_backend(name)
   1260         except ImportError as exc:
   1261             if force:

~/anaconda3/envs/blechpy/lib/python3.7/site-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    235                 "Cannot load backend {!r} which requires the {!r} interactive "
    236                 "framework, as {!r} is currently running".format(
--> 237                     newbackend, required_framework, current_framework))
    238 
    239     rcParams['backend'] = rcParamsDefault['backend'] = newbackend

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

**Comment by nubs01** [comment]
Next time you're in lab, import os
Look at os.Environ['Display'] and remember that value.

Then over ssh you can set os.Environ['Display'] = ':0' and then import
datashader and blechpy. ':0' works for me but it's not true for all monitor
setups so I can build it into the package. There's probably a way to detect
and solve this internally but I don't know it. Likely I'd need to make it
so TkAgg is only used not over ssh, but that breaks a lot of functions.

**Comment by danielsvedberg** [comment]
Stale issue, hasn't been an issue for a while
