### ISSUE TITLE
Cannot uninstall 'llvmlite'. 

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#3]
When running 'pip install blechpy', blechpy fails to install and I get the following error message:

> Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Running Ubuntu 18.04.3 LTS

**Comment by danielsvedberg** [comment]
Circumvented by installing blechpy using trick from this [stackexchange thread](https://stackoverflow.com/questions/12759761/python-pip-force-install-ignoring-dependencies):
`pip install blechpy --ignore-installed llvmlite`

**Comment by nubs01** [comment]
Yeah its probably due to one of the subpackages trying to force a specific
version of llvmlite
