### ISSUE TITLE
make_psth_arrays() IndexError when excluding dig_ins

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#8]
I'm processing several datasets with superfluous dig-in data. In initParams(). I've pasted my error and dig_in_mapping below, but for brevity I think you can fix it by addressing the problem that lies in:
https://github.com/nubs01/blechpy/blob/5c12fa2cbff6510c38bcb8beaac8aef673144928/blechpy/datastructures/dataset.py#L1035-L1039

where 'row' in the dig_ins.iterrows() loop has no condition limiting it to rows where ['exclude'] == False. 

Most thoughtless/easy solution would be to add 
`if row['exclude'] == False:` 
right after https://github.com/nubs01/blechpy/blob/5c12fa2cbff6510c38bcb8beaac8aef673144928/blechpy/datastructures/dataset.py#L1035-L1039 but maybe there's a more elegant solution where you can put the condition in the loop. 

The following is an example of my Digital Input parameters: 

<pre>--------------------
Digital Input
--------------------
 channel  name  palatability_rank  laser  spike_array  exclude  laser_channels
       0   Suc                  0  False         True    False           False
       1  NaCl                  0  False         True    False           False
       2    CA                  0  False         True    False           False
       3  QHCl                  0  False         True    False           False
       4     a                  0  False        False     True           False
       5     b                  0  False        False     True           False
</pre>
(I just now realize for some reason my palatability ranks are nonexistent, but I've fixed that)

When I run make_psth_arrays() I get the following error:

<pre>Exception in blechpy.datastructures.dataset.make_psth_arrays

<font color="#CC0000">---------------------------------------------------------------------------</font>
<font color="#CC0000">NoSuchNodeError</font>                           Traceback (most recent call last)
<font color="#4E9A06">~/anaconda3/envs/blech/lib/python3.7/site-packages/tables/group.py</font> in <font color="#06989A">__getitem__</font><font color="#3465A4">(self, childname)</font>
<font color="#8AE234"><b>    441</b></font>         <font color="#4E9A06">try</font><font color="#3465A4">:</font>
<font color="#4E9A06">--&gt; 442</font><font color="#CC0000">             </font><font color="#4E9A06">return</font> self<font color="#3465A4">.</font>_f_get_child<font color="#3465A4">(</font>childname<font color="#3465A4">)</font>
<font color="#8AE234"><b>    443</b></font>         <font color="#4E9A06">except</font> NoSuchNodeError<font color="#3465A4">:</font>

<font color="#4E9A06">~/anaconda3/envs/blech/lib/python3.7/site-packages/tables/group.py</font> in <font color="#06989A">_f_get_child</font><font color="#3465A4">(self, childname)</font>
<font color="#8AE234"><b>    710</b></font> 
<font color="#4E9A06">--&gt; 711</font><font color="#CC0000">         </font>self<font color="#3465A4">.</font>_g_check_has_child<font color="#3465A4">(</font>childname<font color="#3465A4">)</font>
<font color="#8AE234"><b>    712</b></font> 

<font color="#4E9A06">~/anaconda3/envs/blech/lib/python3.7/site-packages/tables/group.py</font> in <font color="#06989A">_g_check_has_child</font><font color="#3465A4">(self, name)</font>
<font color="#8AE234"><b>    397</b></font>                 <font color="#3465A4">&quot;group ``%s`` does not have a child named ``%s``&quot;</font>
<font color="#4E9A06">--&gt; 398</font><font color="#CC0000">                 % (self._v_pathname, name))</font>
<font color="#8AE234"><b>    399</b></font>         <font color="#4E9A06">return</font> node_type

<font color="#CC0000">NoSuchNodeError</font>: group ``/spike_trains`` does not have a child named ``dig_in_4``

During handling of the above exception, another exception occurred:

<font color="#CC0000">IndexError</font>                                Traceback (most recent call last)
<font color="#4E9A06">&lt;ipython-input-19-611dda804b90&gt;</font> in <font color="#06989A">&lt;module&gt;</font>
<font color="#4E9A06">----&gt; 1</font><font color="#CC0000"> </font>tastes<font color="#3465A4">.</font>make_psth_arrays<font color="#3465A4">()</font>

<font color="#4E9A06">~/Documents/CodeVault/blechpy/blechpy/utils/decorators.py</font> in <font color="#06989A">wrapper</font><font color="#3465A4">(*args, **kwargs)</font>
<font color="#8AE234"><b>     24</b></font>                     sys<font color="#3465A4">.</font>stdout <font color="#3465A4">=</font> old_out
<font color="#8AE234"><b>     25</b></font>                     <font color="#4E9A06">if</font> fail <font color="#4E9A06">is</font> <font color="#4E9A06">not</font> <font color="#4E9A06">False</font><font color="#3465A4">:</font>
<font color="#4E9A06">---&gt; 26</font><font color="#CC0000">                         </font><font color="#4E9A06">raise</font> fail
<font color="#8AE234"><b>     27</b></font> 
<font color="#8AE234"><b>     28</b></font>             <font color="#4E9A06">else</font><font color="#3465A4">:</font>

<font color="#4E9A06">~/Documents/CodeVault/blechpy/blechpy/utils/decorators.py</font> in <font color="#06989A">wrapper</font><font color="#3465A4">(*args, **kwargs)</font>
<font color="#8AE234"><b>     16</b></font>                     sys<font color="#3465A4">.</font>stdout <font color="#3465A4">=</font> f
<font color="#8AE234"><b>     17</b></font>                     <font color="#4E9A06">try</font><font color="#3465A4">:</font>
<font color="#4E9A06">---&gt; 18</font><font color="#CC0000">                         </font>func<font color="#3465A4">(*</font>args<font color="#3465A4">,</font> <font color="#3465A4">**</font>kwargs<font color="#3465A4">)</font>
<font color="#8AE234"><b>     19</b></font>                         fail <font color="#3465A4">=</font> <font color="#4E9A06">False</font>
<font color="#8AE234"><b>     20</b></font>                     <font color="#4E9A06">except</font> Exception <font color="#4E9A06">as</font> e<font color="#3465A4">:</font>

<font color="#4E9A06">~/Documents/CodeVault/blechpy/blechpy/datastructures/dataset.py</font> in <font color="#06989A">make_psth_arrays</font><font color="#3465A4">(self)</font>
<font color="#8AE234"><b>   1037</b></font>                                                   params<font color="#3465A4">[&apos;window_size&apos;],</font>
<font color="#8AE234"><b>   1038</b></font>                                                   params<font color="#3465A4">[&apos;window_step&apos;],</font>
<font color="#4E9A06">-&gt; 1039</font><font color="#CC0000">                                                   row[&apos;channel&apos;])</font>
<font color="#8AE234"><b>   1040</b></font> 
<font color="#8AE234"><b>   1041</b></font>         self<font color="#3465A4">.</font>process_status<font color="#3465A4">[&apos;make_psth_arrays&apos;]</font> <font color="#3465A4">=</font> <font color="#4E9A06">True</font>

<font color="#4E9A06">~/Documents/CodeVault/blechpy/blechpy/analysis/spike_analysis.py</font> in <font color="#06989A">make_psths_for_tastant</font><font color="#3465A4">(h5_file, win_size, win_step, dig_in_ch, smoothing_width)</font>
<font color="#8AE234"><b>     74</b></font>     dig_str <font color="#3465A4">=</font> <font color="#3465A4">&apos;dig_in_%i&apos;</font> <font color="#3465A4">%</font> dig_in_ch
<font color="#8AE234"><b>     75</b></font>     <font color="#4E9A06">with</font> tables<font color="#3465A4">.</font>open_file<font color="#3465A4">(</font>h5_file<font color="#3465A4">,</font> <font color="#3465A4">&apos;r+&apos;)</font> <font color="#4E9A06">as</font> hf5<font color="#3465A4">:</font>
<font color="#4E9A06">---&gt; 76</font><font color="#CC0000">         </font>spike_data <font color="#3465A4">=</font> hf5<font color="#3465A4">.</font>root<font color="#3465A4">.</font>spike_trains<font color="#3465A4">[</font>dig_str<font color="#3465A4">]</font>
<font color="#8AE234"><b>     77</b></font>         spike_array <font color="#3465A4">=</font> spike_data<font color="#3465A4">.</font>spike_array<font color="#3465A4">[:]</font>
<font color="#8AE234"><b>     78</b></font>         time <font color="#3465A4">=</font> spike_data<font color="#3465A4">.</font>array_time<font color="#3465A4">[:]</font>

<font color="#4E9A06">~/anaconda3/envs/blech/lib/python3.7/site-packages/tables/group.py</font> in <font color="#06989A">__getitem__</font><font color="#3465A4">(self, childname)</font>
<font color="#8AE234"><b>    442</b></font>             <font color="#4E9A06">return</font> self<font color="#3465A4">.</font>_f_get_child<font color="#3465A4">(</font>childname<font color="#3465A4">)</font>
<font color="#8AE234"><b>    443</b></font>         <font color="#4E9A06">except</font> NoSuchNodeError<font color="#3465A4">:</font>
<font color="#4E9A06">--&gt; 444</font><font color="#CC0000">             </font><font color="#4E9A06">raise</font> IndexError<font color="#3465A4">(</font>childname<font color="#3465A4">)</font>
<font color="#8AE234"><b>    445</b></font> 
<font color="#8AE234"><b>    446</b></font>     <font color="#4E9A06">def</font> _f_walknodes<font color="#3465A4">(</font>self<font color="#3465A4">,</font> classname<font color="#3465A4">=</font><font color="#4E9A06">None</font><font color="#3465A4">):</font>

<font color="#CC0000">IndexError</font>: dig_in_4
</pre>

From this I gathered that make_psth_arrays() is pulling all the rows in dig_ins['channel'] without excluding dig_ins 4 & 5, which have no spike trains because they are superfluous dig_ins.

**Comment by nubs01** [comment]
The proper way is to base it on spike_array being true. The exclude flag is
solely for use in a users personal code for now.
I've updated it and pushed the updates to github. Also released
blechpy 2.0.19. Also updated how HMMs are run.
