### ISSUE TITLE
Condition is always true no matter what

### ISSUE THREAD

**Issue by danielsvedberg** [nubs01/blechpy#9]
https://github.com/nubs01/blechpy/blob/b6ca74051248735e15d719284b8e896ac4d421f8/blechpy/analysis/spike_sorting.py#L41

Seems that no matter if the list is [ ], [''], or [0], the condition passes true, even if there are no laser trials.

**Comment by nubs01** [comment]
It's false if laser_channels is None. What's is laser ch in your params?
